name: Auto Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "✅ SSH connection successful!"
            hostname
            whoami
            uptime

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🚀 Starting deployment..."
            cd /home/ubuntu/monitoring || exit 1

            echo "📦 Pulling latest code..."
            sudo git fetch origin main
            sudo git reset --hard origin/main

            echo "🧱 Rebuilding Docker containers..."
            sudo docker compose down
            sudo docker compose up -d --build

            echo "🔍 Checking container status..."
            sudo docker ps

            echo "✅ Deployment finished successfully!"

      - name: Verify Deployment Health
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🩺 Verifying application health..."
            # Ganti URL di bawah sesuai domain/IP dan port kamu
            curl -f http://localhost:80 || curl -f http://127.0.0.1:80
            echo "✅ Application is responding correctly."
